import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Reads non-Firebase secrets from [.env]. Firebase keys come from
/// [firebase_options.dart] generated by FlutterFire CLI (Owner only).
abstract final class EnvConfig {
  static Future<void> load() async {
    await dotenv.load(fileName: '.env');
  }

  static String get appEnv => dotenv.env['APP_ENV'] ?? 'development';

  static bool get isProduction => appEnv == 'production';

  static String? get admobAppIdAndroid => _optional('ADMOB_APP_ID_ANDROID');

  static String? get admobAppIdIos => _optional('ADMOB_APP_ID_IOS');

  static String? get admobBannerAdUnitId => _optional('ADMOB_BANNER_AD_UNIT_ID');

  static String? get admobInterstitialAdUnitId =>
      _optional('ADMOB_INTERSTITIAL_AD_UNIT_ID');

  static String? get admobRewardedAdUnitId =>
      _optional('ADMOB_REWARDED_AD_UNIT_ID');

  static String? get apiBaseUrl => _optional('API_BASE_URL');

  static String? _optional(String key) {
    final value = dotenv.env[key];
    if (value == null || value.trim().isEmpty) {
      return null;
    }
    return value.trim();
  }
}
